[package]
name = "chess_client"
version = "0.1.0"
authors = ["Gustorn <gustorn@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
stdweb = "0.4.9"
chess_core = { path = "../chess_core" }

[profile.release]
opt-level = 's'
debug = false
lto = true
